SKILLS_KEYWORDS: list[str] = [
  "python",
  "java",
  "javascript",
  "typescript",
  "react",
  "node.js",
  "nodejs",
  "fastapi",
  "django",
  "flask",
  "spring",
  "go",
  "golang",
  "rust",
  "c++",
  "c#",
  "sql",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "docker",
  "kubernetes",
  "aws",
  "gcp",
  "azure",
  "terraform",
  "ansible",
  "ci/cd",
  "git",
  "linux",
  "machine learning",
  "deep learning",
  "pytorch",
  "tensorflow",
  "scikit-learn",
  "pandas",
  "numpy",
  "spark",
  "kafka",
  "airflow",
  "etl",
  "graphql",
  "rest",
  "microservices",
  "vue",
  "angular",
  "tailwind",
  "html",
  "css",
  "next.js",
  "express",
  "elasticsearch",
  "rabbitmq",
  "helm",
  "prometheus",
  "grafana",
]

DEGREE_KEYWORDS: list[str] = [
  "ph.d",
  "phd",
  "doctorate",
  "m.s.",
  "m.s",
  "master",
  "mba",
  "b.tech",
  "btech",
  "b.e.",
  "b.e",
  "bachelor",
  "b.s.",
  "b.s",
  "b.a.",
  "b.a",
  "associate",
]

SECTION_HEADERS: dict[str, list[str]] = {
    "projects": ["projects", "personal projects", "selected projects"],
    "certifications": ["certifications", "licenses", "certificates"],
    "education": ["education", "academic background"],
    "experience": ["experience", "work experience", "professional experience"],
}

ALL_SECTION_HEADERS: list[str] = sorted(
    {header for headers in SECTION_HEADERS.values() for header in headers},
    key=len,
    reverse=True,
)
